// Code generated by encodegen. DO NOT EDIT.
package imported

import (
	"gitlab.com/NebulousLabs/encoding"
	"io"
)

// MarshalSia implements encoding.SiaMarshaler.
func (x Imported) MarshalSia(w io.Writer) error {
	e := encoding.NewEncoder(w)
	e.WriteUint64(uint64(x.A))
	e.WritePrefixedBytes([]byte(x.B))
	e.WriteBool(x.C)
	return e.Err()
}

// UnmarshalSia implements encoding.SiaUnmarshaler.
func (x *Imported) UnmarshalSia(r io.Reader) error {
	d := encoding.NewDecoder(r, encoding.DefaultAllocLimit)
	x.A = int(d.NextUint64())
	x.B = string(d.ReadPrefixedBytes())
	x.C = bool(d.NextBool())
	return d.Err()
}
