// Code generated by encodegen. DO NOT EDIT.
package importedtype

import (
	encodegen "go.sia.tech/encodegen/pkg/encodegen"
)

// MarshalBuffer implements MarshalerBuffer
func (i *Imported) MarshalBuffer(b *encodegen.ObjBuffer) {
	if i != nil {

		b.WriteUint64(uint64(i.A))

		b.WriteUint64(uint64(len(i.B)))
		b.Write(i.B)

	}
}

// UnmarshalBuffer implements encodegen's UnmarshalerBuffer
func (i *Imported) UnmarshalBuffer(b *encodegen.ObjBuffer) error {
	if i != nil {
		var length int = 0
		_ = length

		i.A = int(b.ReadUint64())

		length = int(b.ReadUint64())
		if length > 0 {
			if len(i.B) < length {
				i.B = make([]byte, length)
			}
			i.B = i.B[:length]
			b.Read(i.B)
		}

	}
	return b.Err()
}
